server:
  port: 80

spring:
  application:
    name: cloud-customer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456